# Site settings
title: Class of 2020
email: ncitclassof2020@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We're the NCIT Class of 2020.
baseurl: "/WT-Notes" # the subpath of your site, e.g. /blog
url: "http://ww1.classof2020.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NCIT2020

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
